### PR TITLE
feat(deploy): Update Raspberry Pi Example to Jakarta

### PR DESCRIPTION
**Pull request by AlexCuse**
Use EdgeX 2.1 in examples.

Signed-off-by: Alex Ullrich <alex.ullrich@gmail.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
         - docs change only
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
        - docs change only

### CODE REVIEW

**Comment by AlexCuse** [comment]
@jpwhitemn @lenny-intel just rebased this - is there anything else needed to get it merged in?

**Comment by lenny-intel** [comment]
@AlexCuse , I will leave this to @jpwhitemn and his team that are familiar with Raspberry PI

**Comment by AlexCuse** [comment]
I followed through it this morning to set up a test harness for local `go-mod-messaging` changes and noticed one header was off and I didn't use a 597* port for the app service.  Fixed and rebased the branch while I was at it.

**Comment by AlexCuse** [comment]
@jpwhitemn I have an example in progress to build a "camera trap" using some cheap GPIO sensors and `device-onvif-camera` for #87  - do you think this should be added in addition to this example, or as its own thing that assumes some familiarity?

**Review by bnevis-i — APPROVED** [review]
Please submit a follow on PR to upgrade to go 1.18.

**Comment by bnevis-i** [comment]
@jpwhitemn This has been sitting out where a while now.  Any objections to merging it?

**Comment by AlexCuse** [comment]
I can try to update to 1.18 in this PR that should be pretty quick.

**Comment by AlexCuse** [comment]
Updated to go 1.18 @bnevis-i.  Not doing 2.2 because all my lab stuff is packed for a move and I can't test.  Don't really have the interest in going through it again either, I don't know what the holdup has been here but I kind of regret taking it on.

**Review by bnevis-i — APPROVED** [review]

**Pull request merged**
