### PR TITLE
build: Update Security example to 3.1.0 released images.

### PR DESCRIPTION
**Pull request by lenny-intel**
Removed obsolte compose files and fixed doc  link in README.

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)

### CODE REVIEW

**Comment by bnevis-i** [comment]
> Removed obsolte compose files and fixed doc link in README.

Would you be open to publishing a large context diff instead?  I wanted to show what the specific changes where to enable this functionality.

**Comment by lenny-intel** [comment]
> Would you be open to publishing a large context diff instead?

Not following what you are looking for?

**Review by jim-wang-intel — APPROVED** [review]
LGTM

**Comment by bnevis-i** [comment]
> > Would you be open to publishing a large context diff instead?
> 
> Not following what you are looking for?

`diff -c 10 original-docker-compose.yaml new-docker-compose.yaml > docker-compose.diff`

and check in `docker-compose.diff`

The idea is to show people how to recreate the supplied docker-compose.

**Comment by lenny-intel** [comment]
> The idea is to show people how to recreate the supplied docker-compose.

As part of the tutorial? Not sure the value and it is out of scope for this PR.

**Review by bnevis-i — COMMENTED** [review]
Waive review.

**Pull request merged**
