### PR TITLE
fix: typo in Update 10_install_ubuntu.md

### PR DESCRIPTION
**Pull request by JGrotex**
fix typo

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)

### CODE REVIEW

**Comment by lenny-intel** [comment]
@JGrotex , your commit and PR title must follow the `Conventional Commit` guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/main/.github/Contributing.md

**Comment by JGrotex** [comment]
added just type, as there is no scope for documentations

**Comment by lenny-intel** [comment]
> added just type, as there is no scope for documentations

You also have to amend the commit message.

**Review by lenny-intel — APPROVED** [review]

**Comment by lenny-intel** [comment]
@JGrotex , you add new commit, not amended orginal which is still failing the Semantic validation. Now you must squash your commits and fix the commit message.

**Pull request closed without merging**
